apiVersion: apps/v1
kind: Deployment
metadata:
  name: defectdojo-celery-worker
  labels:
    defectdojo.org/component: celery
    app.kubernetes.io/name: defectdojo
    app.kubernetes.io/instance: defectdojo
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: defectdojo-1.6.200
spec:
  replicas: 1
  selector:
    matchLabels:
      defectdojo.org/component: celery
      app.kubernetes.io/name: defectdojo
      app.kubernetes.io/instance: defectdojo
  template:
    metadata:
      labels:
        defectdojo.org/component: celery
        app.kubernetes.io/name: defectdojo
        app.kubernetes.io/instance: defectdojo
    spec:
      serviceAccountName: defectdojo
      containers:
      - name: celery
        image: "quay-reg-s3-quay-quay-registry.apps.lab.ocp.ad.dom/defectdojo/defectdojo-django:1.6.200"
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000740000
          runAsGroup: 1000740000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          seccompProfile:
            type: RuntimeDefault
        command: ['/entrypoint-celery-worker.sh']
        envFrom:
        - configMapRef:
            name: defectdojo
        - secretRef:
            name: defectdojo-extrasecrets
            optional: true
        env:
        - name: DD_CELERY_BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: defectdojo-redis-specific
              key: redis-password
        - name: DD_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: defectdojo-postgresql-specific
              key: password
        - name: DD_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: defectdojo-secret-key
        - name: DD_CREDENTIAL_AES_256_KEY
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: defectdojo-secret-key
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
